### ISSUE TITLE
default travis setup is broken

### ISSUE THREAD

**Issue by pbauer** [plone/bobtemplates.plone#222]
```
$ python bootstrap-buildout.py

python: can't open file 'bootstrap-buildout.py': [Errno 2] No such file or directory
```

**Comment by MrTango** [comment]
is this still valid?
I'm not sure if I understand what you mean by default travis setup.
The build is green.

**Comment by pbauer** [comment]
Yes. When I create a new package with bobtemplates.plone and want it to be tested by travis this error happens. 

I changed the `.tavis.yml` to this but I don't know about the current best-practice when it comes to travis.

```yml
language: python
sudo: false
cache:
  pip: true
  directories:
  - $HOME/buildout-cache
python:
  - 2.7
matrix:
  fast_finish: true
install:
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - mkdir $HOME/.buildout
  - echo "[buildout]" > $HOME/.buildout/default.cfg
  - echo "download-cache = $HOME/buildout-cache/downloads" >> $HOME/.buildout/default.cfg
  - echo "eggs-directory = $HOME/buildout-cache/eggs" >> $HOME/.buildout/default.cfg
  - python --version
  - virtualenv --version
  - pip install --upgrade virtualenv
  - virtualenv --clear .
  - bin/pip install --upgrade -r requirements.txt
  - bin/buildout -N buildout:download-cache=downloads code-analysis:return-status-codes=True annotate
  - bin/buildout -N buildout:download-cache=downloads code-analysis:return-status-codes=True
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- firefox -v
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage
  - pip install coveralls
  - coveralls
notifications:
  email:
    - bauer@starzel.de
```
